### ISSUE TITLE
Ajouter la possibilité de télécharger le rapport du test

### ISSUE THREAD

**Issue by stuxboulot** [OctoPerf/octoperf-maven-plugin#3]
Avoir dans les artefact le rapport au format HTML permettant de l'archiver automatiquement depuis la pipeline

**Comment by Hanshuit** [comment]
Le rapport n'est pas généré dans le backend, il n'est donc pas disponible au format HTML en dehors du navigateur pour le moment.
Je remonte le point sur OctoPerf d'une manière générale, merci!
